// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv126I3itJb7KQCpIqGPK0VicT3-3BrGc',
    appId: '1:1040911422709:web:3752e57b90962d0acea1bc',
    messagingSenderId: '1040911422709',
    projectId: 'inventory-management-papa',
    authDomain: 'inventory-management-papa.firebaseapp.com',
    databaseURL: 'https://inventory-management-papa-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-papa.appspot.com',
    measurementId: 'G-9V68MMEEXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCazHTxEB8pGer3eKRVuIoD0QAaGwe72M',
    appId: '1:1040911422709:android:605915cf39421fb8cea1bc',
    messagingSenderId: '1040911422709',
    projectId: 'inventory-management-papa',
    databaseURL: 'https://inventory-management-papa-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-papa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztK68DyEdicPO-enzBl4KYCUyNVS9dA4',
    appId: '1:1040911422709:ios:73fd626c827dd69dcea1bc',
    messagingSenderId: '1040911422709',
    projectId: 'inventory-management-papa',
    databaseURL: 'https://inventory-management-papa-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-papa.appspot.com',
    iosClientId: '1040911422709-hk57siss393o3v222tctat6d1rdrlmds.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztK68DyEdicPO-enzBl4KYCUyNVS9dA4',
    appId: '1:1040911422709:ios:73fd626c827dd69dcea1bc',
    messagingSenderId: '1040911422709',
    projectId: 'inventory-management-papa',
    databaseURL: 'https://inventory-management-papa-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-papa.appspot.com',
    iosClientId: '1040911422709-hk57siss393o3v222tctat6d1rdrlmds.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv126I3itJb7KQCpIqGPK0VicT3-3BrGc',
    appId: '1:1040911422709:web:43e214d3a2dd37dfcea1bc',
    messagingSenderId: '1040911422709',
    projectId: 'inventory-management-papa',
    authDomain: 'inventory-management-papa.firebaseapp.com',
    databaseURL: 'https://inventory-management-papa-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-papa.appspot.com',
    measurementId: 'G-TNW496W09X',
  );

}